import { ArrowRight, Image as ImageIcon, Star, Wand2 } from 'lucide-react';
import { useState } from 'react';
import { QUICK_TEMPLATES } from '../../../../data/imageGeneratorMockData';
import { useGeneratedImages } from '../../../../lib/generated-images';

const card = 'rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-[#0c0c14] p-5 sm:p-6';
const label = 'text-[11px] font-black uppercase tracking-[0.18em] text-slate-400 dark:text-slate-500';

export default function DashboardTab({ onNavigate }: { onNavigate: (tab: any) => void }) {
  const { images, loading, error } = useGeneratedImages(); const [prompt, setPrompt] = useState('');
  const recent = images.slice(0, 6); const favorites = images.filter((image) => image.favorite).slice(0, 4);
  return <div className="space-y-8"><div className={card}><p className="text-[11px] font-black uppercase tracking-[.24em] text-purple-600">Workspace overview</p><h2 className="mt-2 text-2xl font-black">What are we creating today?</h2><div className="mt-5 flex gap-3"><input value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder="Describe the image you want to generate..." className="min-w-0 flex-1 rounded-full border border-slate-200 bg-slate-50 px-5 py-3 text-sm dark:border-slate-800 dark:bg-slate-900/60" /><button onClick={() => onNavigate('create')} className="rounded-full bg-purple-700 px-5 py-3 text-xs font-black uppercase text-white"><Wand2 size={15} className="mr-1 inline" />Generate</button></div></div>
  <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{[{label:'Generated images',value:images.length,icon:Wand2},{label:'Favorites',value:favorites.length,icon:Star},{label:'Latest operation',value:images[0]?.operation ?? '—',icon:ImageIcon},{label:'Backend status',value:loading?'Loading':'Connected',icon:ImageIcon}].map(({label: text,value,icon: Icon}) => <div key={text} className={card}><div className="flex justify-between"><span className={label}>{text}</span><Icon size={16} className="text-purple-500" /></div><p className="mt-3 text-2xl font-black capitalize">{value}</p></div>)}</div>
  <div className="grid gap-6 lg:grid-cols-3"><div className={`${card} lg:col-span-2`}><div className="mb-4 flex justify-between"><span className={label}>Quick templates</span><button onClick={() => onNavigate('create')} className="text-xs text-purple-500">Open create <ArrowRight size={12} className="inline" /></button></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{QUICK_TEMPLATES.map((template) => <button key={template.id} onClick={() => onNavigate('create')} className="rounded-xl border border-slate-200 p-3 text-left dark:border-slate-800"><p className="text-xs font-bold">{template.label}</p><p className="mt-1 line-clamp-2 text-[11px] text-slate-400">{template.prompt}</p></button>)}</div></div><div className={card}><span className={label}>Live library</span><p className="mt-4 text-sm text-slate-500">Every image below is loaded from the local backend output manifest.</p></div></div>
  <div className="grid gap-6 lg:grid-cols-2"><div className={card}><div className="mb-4 flex justify-between"><span className={label}>Recent creations</span><button onClick={() => onNavigate('gallery')} className="text-xs text-purple-500">Open gallery</button></div>{error ? <p className="text-sm text-red-500">{error}</p> : recent.length ? <div className="grid grid-cols-3 gap-2">{recent.map((image) => <img key={image.id} src={image.url} alt={image.prompt} className="aspect-square w-full rounded-xl object-cover" />)}</div> : <p className="text-sm text-slate-400">No generated images yet.</p>}</div><div className={card}><span className={label}>Favorites</span>{favorites.length ? <div className="mt-4 grid grid-cols-4 gap-2">{favorites.map((image) => <img key={image.id} src={image.url} alt={image.prompt} className="aspect-square rounded-xl object-cover" />)}</div> : <p className="mt-4 text-sm text-slate-400">Star images in Gallery to keep them here.</p>}</div></div></div>;
}
